### ISSUE TITLE
Example code of loading texture from stb_image without sokol_fetch headers

### ISSUE THREAD

**Issue by Akmal4163** [floooh/sokol-odin#19]
I have attempt to follow code of LearnOpenGL stuff using sokol, i apply it using Odin programming language, so i use sokol odin bindings.

But i have problems when it comes to loading texture, the learnOpenGL example uses sokol_fetch.h, but i find sokol_fetch.h is missing in odin bindings repository.

here is the link of C example that uses sokol_fetch.h :
[https://github.com/zeromake/learnopengl-examples/blob/master/src/1-6-textures/1-texture.c](url)

so i try to load texture using stb_image without sokol_fetch.h, here is link to  my Odin code :

[https://pastebin.com/39Vp8kN7](url)

and here is link to my shader code : 
[https://pastebin.com/CmxYELiy](url)

but when i try to use this code, i find the shapes and texture doesn't appear on the screen , like this : 
![WhatsApp Image 2024-09-15 at 13 47 44](https://github.com/user-attachments/assets/85ef5e64-ad13-42dc-a08f-a53648c9dfff)

is there anything wrong in my code ? if so, how did i load texture without using sokol_fetch.h ? i will appreciate if you provide correct way to doing this.

thank you

**Comment by floooh** [comment]
Hmm, in general using stbi.load() instead of sokol_fetch.h is the right idea.

The C version (stbi_load()) returns a pointer to the loaded pixels:

https://github.com/nothings/stb/blob/f75e8d1cad7d90d72ef7a4661f1b994ef78b4e31/stb_image.h#L1366-L1374

...I suspect that this part in the `sg.init_image()` call is wrong:

```odin
0 = { ptr = &img_data, size = u64(img_width * img_height * 4) }
```

The `ptr = &img_data` initializes ptr with the address of the pointer to the pixel data, but you'd want the address of the pixel data (and the pointer `img_data` already is that address).

Try changing the code like this (you may need some sort of cast though, I don't know Odin all that well besides tinkering with it for the sokol-odin samples):

```odin
0 = { ptr = img_data, size = u64(img_width * img_height * 4) }
```

If you still get a black screen then something else must be wrong though (obviously). It's a bit strange that you're just getting a black screen though. If the above address-of-pointer is the only problem, I would expect some random pixel noise instead of a black screen.

**Comment by floooh** [comment]
Ah, there's something else wrong here which explains the black screen:

```odin
sg.init_image(state.bind.fs.images[SLOT__o_Texture], { ...
```

...this expects that `state.bind.fs.images[SLOT__o_Texture]` is initialized with an image handle, but that doesn't happen anywhere.

I think the above call to `sg.alloc_image()` should look like this instead:

```odin
state.bind.fs.images[SLOT__o_Texture] = sg.alloc_image()
```

...but since you're not using asynchronous file loading, I would suggest to merge the `sg.alloc_image()` and `sg.init_image()` calls into:

```odin
state.bind.fs.images[SLOT__o_Texture] = sg.make_image({
    width = img_width,
    height = img_height,
    data = {
        subimage = {
            0 = {
                0 = { ptr = img_data, size = u64(img_width * img_height * 4) }
            }
        }
    }
}
```

**Comment by floooh** [comment]
...what's strange is that you don't seem to get validation errors though, the sokol_gfx.h validation layer should complain about a missing image binding in the sg.apply_bindings() call.

Are you building in debug mode? (the validation layer is disabled in release mode). TBH though, I never actually checked if the validation layer works in the sokol-odin samples... let me check, one sec...

**Comment by floooh** [comment]
Ok, yeah, the validation layer works as expected, **BUT** you'll need to build with `-debug`, otherwise you'll indeed get black rendering.

For instance I messed up the `texcube` example to not set an image binding, and I get:

```
> odin run ..\examples\texcube -debug

[sg][error][id:267] E:\projects\sokol-odin\sokol\c\sokol_gfx.h(16935):
        VALIDATE_ABND_FS_EXPECTED_IMAGE_BINDING: sg_apply_bindings: image binding on fragment stage is missing or the image handle is invalid

[sg][panic][id:296] E:\projects\sokol-odin\sokol\c\sokol_gfx.h(16168):
        VALIDATION_FAILED: validation layer checks failed

ABORTING because of [panic]
```

...if I just run `odin run ..\examples\texcube` (without the `-debug` arg) I just get a black cube instead of a textured cube.

So definitely make sure to build with `-debug`, otherwise you'll miss a lot of important error information from the sokol-gfx validation layer!

```

**Comment by Akmal4163** [comment]
Thank you for your advice !!!

I tried to follow your code like this : 
`stbi.set_flip_vertically_on_load(1)
    img_width, img_height, nr_channels : i32
    img_data := stbi.load("container.jpg", &img_width, &img_height, &nr_channels, 4)
    defer stbi.image_free(img_data)

    state.bind.fs.images[SLOT__o_Texture] = sg.make_image({
        width = img_width,
        height = img_height,
        data = {
            subimage = {
                0 = {
                    0 = { ptr = img_data, size = u64(img_width * img_height * 4) }
                }
            }
        }
    })
`

finally, this texture appear on the screen.
![WhatsApp Image 2024-09-16 at 12 35 25](https://github.com/user-attachments/assets/d4a3b2de-4e14-4d93-ade9-7eee280ab040)

**Comment by Akmal4163** [comment]
Thank you for your advice !!!

I tried to follow your code like this : 
`stbi.set_flip_vertically_on_load(1)
    img_width, img_height, nr_channels : i32
    img_data := stbi.load("container.jpg", &img_width, &img_height, &nr_channels, 4)
    defer stbi.image_free(img_data)

    state.bind.fs.images[SLOT__o_Texture] = sg.make_image({
        width = img_width,
        height = img_height,
        data = {
            subimage = {
                0 = {
                    0 = { ptr = img_data, size = u64(img_width * img_height * 4) }
                }
            }
        }
    })
`

finally, this texture appear on the screen.
![WhatsApp Image 2024-09-16 at 12 35 25](https://github.com/user-attachments/assets/d4a3b2de-4e14-4d93-ade9-7eee280ab040)
