### ISSUE TITLE
Is it possible to include utility libraries in the bindings too?

### ISSUE THREAD

**Issue by pnarimani** [floooh/sokol-odin#23]
I have been trying to integrate Dear ImGUI and Sokol for a while now and after looking at examples on this repo and a lot more I have had no success. 
My problem specifically is that Odin ImGUI integrations expect to be initialized using a backend but I can't seem to figure out how to get that backend from Sokol. (This is the odin bindings that I'm using for ImGUI: https://gitlab.com/L-4/odin-imgui).

This is honestly due to my knowledge gap in how Dear ImGUI works and I'm actively trying to learn, but for now since I had no luck with the integration, I'm wondering if it's possible to add the utility libraries from the main sokol repository to the binding generator so we don't have to use two separate repositories to use them together?

**Comment by floooh** [comment]
Adding imgui-support to the bindings is tricky because building the bindings C library requires access to the Dear ImGui source tree (and I don't want to add a Dear ImGui submodule to the sokol-odin bindings).

In sokol-zig this is solved with the Zig dependency manager and some build system magic (basically, 'bring your own imgui dependency' which then needs to be injected into the sokol dependency build process), but I don't know how the same problem could be solved with Odin.

What *can* be done of course is to simply add a code-generated imgui.odin module to the bindings, and leave the rest as excercise to the user, not sure how helpful that would be though.

**Comment by pnarimani** [comment]
I realized that the portion of the code that I have to rewrite from sokol_imgui to odin is just the input event handling. Other than that, I can get the device context from sokol based on the platform and feed it to imgui. 
I'm gonna close this ticket. Thanks!

**Comment by AlexanderArvidsson** [comment]
@pnarimani As someone just starting to look into adding imgui, any pointers you can give here would be greatly appreciated!
I'd be more than happy to contribute to sokol-odin to automate this process so anyone can start out quickly with imgui.

Did you end up using odin-imgui and just rewriting the input event handling from sokol_imgui, or did you do something else?

**Comment by AlexanderArvidsson** [comment]
After a bit of hacky tinkering, I got something working:
![image](https://github.com/user-attachments/assets/96f0fedd-333c-4c33-895f-f7959b649f39)

This uses @floooh's auto-generated imgui bindings (I enabled it manually in bindgen).
You still need the imgui bindings, I started off with https://gitlab.com/L-4/odin-imgui, but had to do some modifications, going to look for a better way here.

I'm thinking of creating a separate repo (sokol-odin-imgui) that does all the necessary steps, and integrates into the bindgen'd sokol_imgui stuff, if you're up for it. This might be able to be merged into sokol-odin later, it depends.
I think a good first step is to add the code-generated sokol_imgui stuff, maybe behind a flag, so there's at least a possibility for users to generate them. 

If I can't figure out a clean and automated way to integrate it, I could at least write a guide somewhere for people wanting to get it running.

**Comment by AlexanderArvidsson** [comment]
> @AlexanderArvidsson Have you got any steps for how you got this set up? Would appreciate any help as I'm stuck on linking the odin-imgui after having built the sokol imgui odin file.

My previous comment was done with a bunch of hacks, I'm working on a much easier method right now. While I got it working now with a better method, I'm running into an issue with displaying images with the sokol_imgui bindings.

@floooh Would you happen to have any insights into the following error?
```
game_hot_reload.bin: c/sokol_gfx.h:16355: _sg_image_at: Assertion `(slot_index > (0)) && (slot_index < p->image_pool.size)' failed.
```

Here's the my setup this:
```
	img_desc := sg.Image_Desc {
		render_target = true,
		width         = i32(constants.VIEWPORT_SIZE[0]),
		height        = i32(constants.VIEWPORT_SIZE[1]),
		pixel_format  = .RGBA16F,
		sample_count  = constants.OFFSCREEN_SAMPLE_COUNT,
	}
	state.image.img_color = sg.make_image(img_desc)
	state.image.tex_id_color = simgui.imtextureid_with_sampler(state.image.img_color, smp_filter)
```

Here's the rendering for imgui:
```
	ig.SetNextWindowPos(ig.Vec2{10, 10}, .Once)
	ig.SetNextWindowSize(ig.Vec2{400, 100}, .Once)
	ig.Begin("Hello Dear ImGui!")
	ig.ColorEdit3("Background", &state.color)
	fmt.println(state.image.tex_id_color)
	ig.Image(&state.image.tex_id_color, ig.Vec2{100, 100})
	ig.End()
```

The above println gets me `281492156645380`.

They should be bound in my current pass

I've added some debug prints right before the assertion in sokol_gfx `_sg_image_at` so you can see what slot it's trying to use right before the error:
```
Slot: 37632, image ID: 1886032640, pool size: 129, invalid slot index: 0
game_hot_reload.bin: c/sokol_gfx.h:16355: _sg_image_at: Assertion `(slot_index > (0)) && (slot_index < p->image_pool.size)' failed.
```

In order to make sokol_imgui use odin-imgui, I had to also set `-DImTextureID=uint64_t`, since that is what `simgui_imtextureid_with_sampler` and `simgui_imtextureid` and ultimately what is needed for this line (`c/sokol_imgui.h:2596:22`):
```
    io->Fonts->TexID = simgui_imtextureid_with_sampler(_simgui.font_img, _simgui.font_smp);
```
which sets up the font texture (which is working as I can see the text in imgui).

Trying to investigate what the cause for this is. I used both the [zig example](https://github.com/floooh/sokol-zig-imgui-sample/blob/main/src/main.zig) and the [imgui-images-sapp.c](https://github.com/floooh/sokol-samples/blob/master/sapp/imgui-images-sapp.c) sample.
Could it be due to how I'm building imgui into sokol?

**Comment by pnarimani** [comment]
The way I set it up is like this:
init:
```
	im.CHECKVERSION()
	im.CreateContext()
	io := im.GetIO()
	io.ConfigFlags += {.NavEnableKeyboard, .NavEnableGamepad}
	io.ConfigFlags += {.DockingEnable}
	io.ConfigFlags += {.ViewportsEnable}
	io.BackendFlags += {.RendererHasVtxOffset}

	style := im.GetStyle()
	style.WindowRounding = 0
	style.Colors[im.Col.WindowBg].w = 1
	im.StyleColorsDark()

	im_win32.Init(auto_cast sapp.win32_get_hwnd())
	im_dx.Init(auto_cast sapp.d3d11_get_device(), auto_cast sapp.d3d11_get_device_context())
```

and this is the event handler (this event handler uses absolute positions for mouse position since I'm using viewports feature):
```
package main

import im "../vendor/odin-imgui"
import sapp "../vendor/sokol-odin/sokol/app"
import "core:c"
import "core:fmt"


add_touch_pos :: proc(x, y: f32) {
	using im
	io := GetIO()
	IO_AddMouseSourceEvent(io, .TouchScreen)
	IO_AddMousePosEvent(io, x, y)
}

add_mouse_pos :: proc(x, y: f32) {
	using im
	io := GetIO()
	IO_AddMouseSourceEvent(io, .Mouse)
	abs_x, abs_y := transform_mouse_pos(x, y)
	IO_AddMousePosEvent(io, abs_x, abs_y)
}

add_mouse_button :: proc(button: i32, down: bool) {
	io := im.GetIO()
	im.IO_AddMouseSourceEvent(io, .Mouse)
	im.IO_AddMouseButtonEvent(io, cast(c.int)button, down)
}

add_touch_button :: proc(button: i32, down: bool) {
	io := im.GetIO()
	im.IO_AddMouseSourceEvent(io, .TouchScreen)
	im.IO_AddMouseButtonEvent(io, cast(c.int)button, down)
}

add_mouse_wheel :: proc(x, y: f32) {
	io := im.GetIO()
	im.IO_AddMouseSourceEvent(io, .Mouse)
	im.IO_AddMouseWheelEvent(io, x, y)
}

add_focus :: proc(focus: bool) {
	io := im.GetIO()
	im.IO_AddFocusEvent(io, focus)
}

update_modifiers :: proc(mod: u32) {
	io := im.GetIO()
	im.IO_AddKeyEvent(io, .ImGuiMod_Ctrl, (mod & sapp.MODIFIER_CTRL) != 0)
	im.IO_AddKeyEvent(io, .ImGuiMod_Shift, (mod & sapp.MODIFIER_SHIFT) != 0)
	im.IO_AddKeyEvent(io, .ImGuiMod_Alt, (mod & sapp.MODIFIER_ALT) != 0)
	im.IO_AddKeyEvent(io, .ImGuiMod_Super, (mod & sapp.MODIFIER_SUPER) != 0)
}

add_key :: proc(key: sapp.Keycode, down: bool) {
	imgui := map_key_code(key)
	im.IO_AddKeyEvent(im.GetIO(), imgui, down)
}

add_input :: proc(c: u32) {
	im.IO_AddInputCharacter(im.GetIO(), c)
}

handle_event :: proc(e: ^sapp.Event) -> bool {
	dpi: f32 = sapp.dpi_scale()
	io := im.GetIO()

	// NOTE: missing touch
	#partial switch e.type {
	case .FOCUSED:
		add_focus(true)
	case .UNFOCUSED:
		add_focus(false)
	case .MOUSE_DOWN:
		add_mouse_pos(e.mouse_x / dpi, e.mouse_y / dpi)
		add_mouse_button(i32(e.mouse_button), true)
		update_modifiers(e.modifiers)
	case .MOUSE_UP:
		add_mouse_pos(e.mouse_x / dpi, e.mouse_y / dpi)
		add_mouse_button(i32(e.mouse_button), false)
		update_modifiers(e.modifiers)
	case .MOUSE_MOVE:
		add_mouse_pos(e.mouse_x / dpi, e.mouse_y / dpi)
	case .MOUSE_SCROLL:
		add_mouse_wheel(e.scroll_x, e.scroll_y)
	case .KEY_DOWN:
		update_modifiers(e.modifiers)
		add_key(e.key_code, true)
	case .KEY_UP:
		update_modifiers(e.modifiers)
		add_key(e.key_code, false)
	case .CHAR:
		update_modifiers(e.modifiers)
		if e.char_code >= 32 &&
		   e.char_code != 127 &&
		   0 == (e.modifiers & (sapp.MODIFIER_ALT | sapp.MODIFIER_CTRL | sapp.MODIFIER_SUPER)) {
			add_input(e.char_code)
		}
	}

	return io.WantCaptureKeyboard || io.WantCaptureMouse
}

transform_mouse_pos :: proc(x, y: f32) -> (f32, f32) {
	if im.ConfigFlags.ViewportsEnable in im.GetIO().ConfigFlags {
		p := im.GetMainViewport().Pos
		return p.x + x, p.y + y
	}

	return x, y
}

map_key_code :: proc(key: sapp.Keycode) -> im.Key {
	#partial switch key {
	case .SPACE:
		return .Space
	case .APOSTROPHE:
		return .Apostrophe
	case .COMMA:
		return .Comma
	case .MINUS:
		return .Minus
	case .PERIOD:
		return .Apostrophe
	case .SLASH:
		return .Slash
	case ._0:
		return ._0
	case ._1:
		return ._1
	case ._2:
		return ._2
	case ._3:
		return ._3
	case ._4:
		return ._4
	case ._5:
		return ._5
	case ._6:
		return ._6
	case ._7:
		return ._7
	case ._8:
		return ._8
	case ._9:
		return ._9
	case .SEMICOLON:
		return .Semicolon
	case .EQUAL:
		return .Equal
	case .A:
		return .A
	case .B:
		return .B
	case .C:
		return .C
	case .D:
		return .D
	case .E:
		return .E
	case .F:
		return .F
	case .G:
		return .G
	case .H:
		return .H
	case .I:
		return .I
	case .J:
		return .J
	case .K:
		return .K
	case .L:
		return .L
	case .M:
		return .M
	case .N:
		return .N
	case .O:
		return .O
	case .P:
		return .P
	case .Q:
		return .Q
	case .R:
		return .R
	case .S:
		return .S
	case .T:
		return .T
	case .U:
		return .U
	case .V:
		return .V
	case .W:
		return .W
	case .X:
		return .X
	case .Y:
		return .Y
	case .Z:
		return .Z
	case .LEFT_BRACKET:
		return .LeftBracket
	case .BACKSLASH:
		return .Backslash
	case .RIGHT_BRACKET:
		return .RightBracket
	case .GRAVE_ACCENT:
		return .GraveAccent
	case .ESCAPE:
		return .Escape
	case .ENTER:
		return .Enter
	case .TAB:
		return .Tab
	case .BACKSPACE:
		return .Backspace
	case .INSERT:
		return .Insert
	case .DELETE:
		return .Delete
	case .RIGHT:
		return .RightArrow
	case .LEFT:
		return .LeftArrow
	case .DOWN:
		return .DownArrow
	case .UP:
		return .UpArrow
	case .PAGE_UP:
		return .PageUp
	case .PAGE_DOWN:
		return .PageDown
	case .HOME:
		return .Home
	case .END:
		return .End
	case .CAPS_LOCK:
		return .CapsLock
	case .SCROLL_LOCK:
		return .ScrollLock
	case .NUM_LOCK:
		return .NumLock
	case .PRINT_SCREEN:
		return .PrintScreen
	case .PAUSE:
		return .Pause
	case .F1:
		return .F1
	case .F2:
		return .F2
	case .F3:
		return .F3
	case .F4:
		return .F4
	case .F5:
		return .F5
	case .F6:
		return .F6
	case .F7:
		return .F7
	case .F8:
		return .F8
	case .F9:
		return .F9
	case .F10:
		return .F10
	case .F11:
		return .F11
	case .F12:
		return .F12
	case .KP_0:
		return .Keypad0
	case .KP_1:
		return .Keypad1
	case .KP_2:
		return .Keypad2
	case .KP_3:
		return .Keypad3
	case .KP_4:
		return .Keypad4
	case .KP_5:
		return .Keypad5
	case .KP_6:
		return .Keypad6
	case .KP_7:
		return .Keypad7
	case .KP_8:
		return .Keypad8
	case .KP_9:
		return .Keypad9
	case .KP_DECIMAL:
		return .KeypadDecimal
	case .KP_DIVIDE:
		return .KeypadDivide
	case .KP_MULTIPLY:
		return .KeypadMultiply
	case .KP_SUBTRACT:
		return .KeypadSubtract
	case .KP_ADD:
		return .KeypadAdd
	case .KP_ENTER:
		return .KeypadEnter
	case .KP_EQUAL:
		return .KeypadEqual
	case .LEFT_SHIFT:
		return .LeftShift
	case .LEFT_CONTROL:
		return .LeftCtrl
	case .LEFT_ALT:
		return .LeftAlt
	case .LEFT_SUPER:
		return .LeftSuper
	case .RIGHT_SHIFT:
		return .RightShift
	case .RIGHT_CONTROL:
		return .RightCtrl
	case .RIGHT_ALT:
		return .RightAlt
	case .RIGHT_SUPER:
		return .RightSuper
	case .MENU:
		return .Menu
	case:
		return .None
	}

	return .None
}
```

I have not tried displaying images or loading fonts yet. But that shouldn't be difficult since ImGUI has nothing to do with rendering. It's just passing around a texture id that you can interpret however you want.

**Comment by AlexanderArvidsson** [comment]
@pnarimani This is great, thank you! Could you try passing a texture to imgui and have sokol render it in the imgui window?
I can't see any render calls in your snippets you've shared.

I'm trying to make the official sokol_imgui bindings work together with odin-imgui rather than re-implement what they do like your method, just the images are not interpreted correctly between the two or something as I'm getting that weird slot issue. It would be great to find out if that is due to my interactions between sokol_imgui and odin-imgui or if there's something else wrong.

**Comment by AlexanderArvidsson** [comment]
@ottah @pnarimani 

I've got a fork of `sokol-odin` with support for ImGui on Linux using the official `sokol_imgui` bindings, I will make sure MacOS works later as well.
I don't have a readily available Windows computer to implement the building there, but it should be relatively straightforward for anyone by just checking how I did it for Linux and MacOS.

I've written a [guide in the README](https://github.com/AlexanderArvidsson/sokol-odin/tree/feature/imgui-lib?tab=readme-ov-file#dear-imgui-support), and added an [example](https://github.com/AlexanderArvidsson/sokol-odin/blob/feature/imgui-lib/examples/imgui/imgui.odin) you can check as well. If you want to try the example, just clone [odin-imgui](https://gitlab.com/L-4/odin-imgui) to the root, build it, and then run the example.

**Comment by AlexanderArvidsson** [comment]
@ottah Great work! There's a couple of problems I can see right off the bat (no pun intended) , I can clean it up and you can give my version a try later.

Here's some problems I see just from glance:
1. IMGUI_PATH is always defined, the idea is if it isn't defined, it should compile the normal libraries without imgui, but if it is defined, it should only compile imgui. Your version will compile all libs at once including imgui, but that's a bit unnecessary. 
2. It includes all imgui objects in all libraries, that can cause problems and uses unnecessary space. See my script how I toggle the params.
3. You can combine all for loops into one single loop compiling all variations, see my script.

Other than that I think it's on the right path!

However, I was doing some experiments including ImGuizmo and I believe this method I chose could cause problems, as we are including imgui inside sokol rather than individually as a separate library. I'll have to think a bit more if this is really the correct approach.

**Comment by AlexanderArvidsson** [comment]
I got my windows laptop set up to build sokol (god I hate windows) and finished up the script.
I actually decided against my route of having the script either build sokol or sokol_imgui, and instead have it add imgui (much like yours). Reason is that the windows shared dll needs to build the whole app + imgui depending on if IMGUI_PATH is set or not.

I'm probably gonna do the same on MacOS, and also revise the shared libraries on linux. My recent PR for linux shared libs creates a shared lib for each sokol package, which isn't in line with Mac and Windows, and I think it makes more sense to have one dynamic library than multiple.

Anyway, I [updated my branch](https://github.com/AlexanderArvidsson/sokol-odin/commit/2f110cec6db62b18fe50057a1a4d086c04ae34fe) with the new windows script. Please give it a try @ottah, it should work out of the box!

**Comment by AlexanderArvidsson** [comment]
@ottah Great! I'll have a extra look on the flags in case I changed anything by accident.

So the final things left to do here:
1. I found out I actually don't need to link in the imgui obj files into sokol, that is linked via odin-imgui, so the sokol lib files don't need any resolved symbols in its lib. That also means we can lessen the requirements for the build (absolute path, missing files, etc). 
2. Consolidate the dynamic libs across all OS:s, especially Linux.
3. Maybe use a flag instead of env variable

I'll get the rest of this sorted and the make a PR.

**Comment by nadako** [comment]
I've tried using it with `-define:SOKOL_DLL=true` and it didn't work, imgui context was null (on the included demo that works without SOKOL_DLL).

I wonder if it's related to this:
> I found out I actually don't need to link in the imgui obj files into sokol, that is linked via odin-imgui, so the sokol lib files don't need any resolved symbols in its lib. That also means we can lessen the requirements for the build (absolute path, missing files, etc).

My set up is rather specific. I'm trying to have hot-reloading, so I use sokol as a dll, and then the main program loads game dll that uses sokol+imgui+simgui. Could it be that because of the statically linked imgui by odin-imgui there are two imguis - one in sokol dll and and one in my game dll, and only the former one gets actually initialized? :)

**Comment by nadako** [comment]
Ended up porting just simgui to odin, seems to work, here is it for anyone interested: https://github.com/nadako/sokol-imgui-odin-port

**Comment by pnarimani** [comment]
@nadako for hot reload I just reinitialize ImGui context on each reload. seems to work fine.
